Algoritmo "semnome"
// Disciplina   : [ Lógica de Programação ]
// Professor   : Rafael Lima 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/11/2021
Var
 n1:inteiro

Inicio
  escreval("escreva sua idade")
  leia(n1)
  
  se (n1<= 5) ou (n1>=60) entao
  escreva("voce tem direito a gratuidade")
  senao
      escreva("voce não tem direito a gratuidade")
  fimse
Fimalgoritmo