Algoritmo "semnome"

Var
  n1,n2: inteiro

Inicio
    escreval(" digite um numero")
    leia(n1)
    escreval("digite um numero")
    leia(n2)
    se (n1 > n2) então
    escreval("digite o 1º numero")
    leia(n1)
    escreval("digite o 2º numero")
    leia(n2)
    se(n1 > n2) então
       escreval(n1," é o numero maior")
          senão
           escreval("n2, é o numero menor")
    fimse
Fimalgoritmo